[project]
name = "sample-talk"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "shrecc>=0.1.1",
]

[tool.environ]
display-name = "Brightcon 2026 Shrek"
