# display-name: fmlca
name: fmlca
channels:
  - conda-forge
dependencies:
  - python=3.12
  - numpy=2.*
  - pandas=2.2.*
  - matplotlib=3.9.*
  - pip:
      - fmpy==0.3.29
      - fmlca==1.0.0
